#ENC[AES256_GCM,data:oHwbtOatNgCLPYYST85ujGP986J3jIvGyUH+5+3DEFwkovP6y/iMRLF/ZHR9QGrysye12tIsEzYge8LLWnESYAUwzFQ=,iv:VhrOTf8KU6dlUNJJO6BCfG/YeFJdq6uxiw8333UKJlg=,tag:JKP+QOi3yLsUUtabjDf+cw==,type:comment]
#
#ENC[AES256_GCM,data:y0Gkl03BdgLh/Si8/v0ImqfiPEqS/9Xc5OfaSG68+xMiDyJiOymMUWQXjUl34BOBAo50kICBIP2MJMWgNY4FWPNv6ZaYGjaoyXg=,iv:KzDLm+mO2axV10BKOmn6Icl5YnWviykkNUSHXWX1V5E=,tag:X9hoFVHTmgjH+AdUjUWujg==,type:comment]
#ENC[AES256_GCM,data:SSLsbEmsR5XGyY7nGi6FgleGuy0BRbktpuxe5oUYi02fzhMUTH1QuQjahxgsYfK9Iw11h2uTrEwCYzyZwx7lxmVvSww=,iv:fKSZZ0GWtpHIGUGyaxzRNqVnQ/7ZOwGwMsGSxo5p+gM=,tag:b9Z92Rt+3OcHIcEr6WZIDg==,type:comment]
#ENC[AES256_GCM,data:B/4TAgfweVrfsmZ9zyaYS/EpMmWFdW90exEJGbPKqrz2,iv:j4z/NJmaXb4HMZw/SJwYhM9WA9JhXXBhEO7k2itoeiE=,tag:xV84/Zu2m55vZY8KZL+uug==,type:comment]
apiVersion: ENC[AES256_GCM,data:Hdw=,iv:svEKQgq95AdMjLJPIh1w822bycyq2puBpV8mwpI5VsY=,tag:bDuxBiQzJYJ1Y4dGDxJaUQ==,type:str]
kind: ENC[AES256_GCM,data:XlhBsoYZ,iv:yzYqd9Qv3TxMwIV/3zVgiEfilQA/sZrlHymaZQKXsb4=,tag:0pge0U3Be9o2wzTi164r+w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:SNbQaZL3pVEbf6ZUFDNbJcm1,iv:go/9Zz1rMoAKbELbwBYU+4E3ZvbUg+/+LMeECwP1XOM=,tag:v3OT6JthK9A3EmxhCckNoQ==,type:str]
    namespace: ENC[AES256_GCM,data:/bY89siUcPDZmA==,iv:rYdw3BEJTku29bFGAp5JCBGSDZO1rcB6DZCidHEnJug=,tag:FJqZ7cLsXYyi97vCal5MPw==,type:str]
stringData:
    PGDATABASE: ""
    PGUSER: ""
    PGPASSWORD: ""
sops:
    age:
        - recipient: age19ucefxcdyvvyp373ghd4crdyudgw3l7adxneu3wmvus4vu3z5c5qqdm7cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcnArWEZmbEVKOVkzUTBD
            bCtGMXFNRzRsL1NZQUxDWnl3RG9tNk5TTFJFCm8rT0VuV3UvV3Z2bTAwdTV6WXYx
            UmdxM0djZ1hVYi8yY2xwc2taSlhNRGsKLS0tICtWb3Jra2dDa0w3WGRoL3Y4YnhJ
            RjNQWUxHYzJ6UklVK2J6bUtrN0FXc2sKOXyMIltbdKV9WhKgOsHbQhdU1rAwscyI
            jEZ4RBHfqibwfyC+xwTDpf4aL01YW4KfH4GTGVXAM5rAWYIWGyqUbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T14:25:03Z"
    mac: ENC[AES256_GCM,data:wPfQgmMCjuYpnyEZTWVzPUzQ6yQFWDKt0AJlKsyzVIZhuCMMHI/VUjWFzuMSY6lMR9tBkK6MRHfg46naCpeiBPFM44D7rXHXVzSShLcLhNl9/LoIXW4wvHL6Sk5NrdQTvX4jAFLXhDVxzgoVQqNKjg16ccQqnYEivEnhyQwGQxk=,iv:/w9FYgYTWOmSBDgW92Xcn4scQgy9v0p7RqXfQKgc+rQ=,tag:xtJl7J1EhXdw5QKA/IUfjA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
