#ENC[AES256_GCM,data:R8UvwBZ9vqoU/EaNYZW5LCLiMQWmlGTYrkfjCOuP8I2ZlvQGHB7QUdDc6DscixJPp041wK9jPobrBrYLifZ4eNBL9Dg=,iv:+omuFEW4iYg255ULBZ0s29PE91sJ6M02ag6uCqQPmcs=,tag:LzWITOdAYR4W6YUzmggvPw==,type:comment]
#
#ENC[AES256_GCM,data:tOxBuXhdWjmCby179Kc3KZdMPGtXYyMBDQ8a6D0QXo16CJO/Vfb5hGYJdSvaJTLSA26GX4WbK+wNTCsyp9sSahWotRkzPBOXWDI=,iv:nlZbc6AfJuVMu2qxQhjIsSQGwEh8vrs4H+oJNKACjBU=,tag:PTckAs0MYaE38zM0frM2yw==,type:comment]
#ENC[AES256_GCM,data:rrefcUUpyE8vL4bzVbt/yPyvakP2fM9MSXVCXJKzrjBDVXMQhU1g6Vmuax02iFu0sujs7NbhnphgstK8T93CgVfQquE=,iv:w3QS9oltLbeR+B4c67ThaO3mmM7ZDk54e32qdQyYUHo=,tag:m1NA5Gu1yeO+m4waUKIkHw==,type:comment]
#ENC[AES256_GCM,data:nk+UbDLMduV5pTV0PlbIjzSNqc8BgLhSLtox8/qV8vil,iv:ETotxd5Sfgn7mhkeTuGLVTdd9xfyDbWn0zyq86+2wZM=,tag:DA5jvL/cNdNOBE5NgGkrIA==,type:comment]
apiVersion: ENC[AES256_GCM,data:FsM=,iv:wSbgqycBQYq7xgZETtdVl+p0wS/m5ji02XYcItcbqpM=,tag:tnfTpOcLUn7inZdGFnlHEw==,type:str]
kind: ENC[AES256_GCM,data:kg6xMxiZ,iv:AY+LrfaXtiicNkgRJqObXQ61jbgYoloTFX/J7uYgmgs=,tag:evRu9WlfAe/A42eRA9JDlg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:VKyt59ytdTV5jYUgO+rBRHwA,iv:cno3BzbrKvC4+nmQwgg2EpOiaYHijTGYswo5ar0rW6Y=,tag:adk7pWfLx7svOsKNLlbQYg==,type:str]
    namespace: ENC[AES256_GCM,data:o0EB5uhAjj8qtw==,iv:IzRP2dGgGbV1r9ZGeIgOuRhbMPkqD9P7F/6r/9Lw2us=,tag:qkhv7OYWKBPhrAfEofMo6Q==,type:str]
stringData:
    PGDATABASE: ENC[AES256_GCM,data:LcxLL3upZA/YdA==,iv:y3Pt3je4844iIiZfo+i3KRhdSf8lwV0/rSNIOv4WAkI=,tag:dHNf1qT/32fqzOOmXFgYrA==,type:str]
    PGUSER: ENC[AES256_GCM,data:lmbjxxz9GC0OAw==,iv:G14NWA5/3G6IK8dyEsqt2IEcM7nzsfKWNIUqZQkwUS0=,tag:Sk7Q6woypC5tBUbHp/96Aw==,type:str]
    PGPASSWORD: ENC[AES256_GCM,data:K3TzfKP1pFeIhaBdq6AC5Q==,iv:f6RkUNImqQofL9VDUpj64e1lR+c4jVEj3GrkKwzMb+0=,tag:LZLEE4RNyl0dEaK57SX4Uw==,type:str]
sops:
    age:
        - recipient: age19ucefxcdyvvyp373ghd4crdyudgw3l7adxneu3wmvus4vu3z5c5qqdm7cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFOS9ibG9VNXpZbWJldytV
            WUZ5eDRmcnNxamZCQ2tadWpoMjFGY0ZiOXdnCk9CL01XY0FSenNnL3dxNCtKV0JF
            NEN3YWgxQjB4R2RHTEdCazJNTlU4RGsKLS0tIDlzNXNaV1dDbWJYakJXMGFZamRR
            emJkdncyVVR2S3NQbXZGUS9rTlNNOEUKLZHZ20jvT4UjEyikQiiaoDw6k3YPrasD
            iMuwjGp/NSlInJWnJ+qTpQaPxYIPL3s4fF7+E1oiZY2HD8tG3W5R0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-25T13:44:55Z"
    mac: ENC[AES256_GCM,data:uZFieob4I1nqULYU61XVprAtA5uVyWs/x69sQTutFrEb1+r5ffxdL8cP04aD49uhACTOw4aLQ2DWKwcHP8F3nsrCXVBoiuaLJoUcwsbfGnLm06FGcMGnN3NlmIhx6963DPkk13lCXWM1Mhil/fzkiTVUH4Iu4FHU88Vth8TUQck=,iv:coE3RhJyyYViOZEcGS6ixf3mdBOjwvdsSNem1YupbtU=,tag:fFciXuE+Ab/nzrAkCNKj2w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
