#ENC[AES256_GCM,data:vDy5Nip7G7fsOzEN7HTiiB/K5Nj3bstsX20KpahqV6mqFfjYkamBlX7kTupBrJqSVm1bV/6HaFlRedLl6wXk3z8=,iv:RgUew41opPVlAd7Sa0eT/vVH4D/HhCrW6kxNKwR3dMA=,tag:ilUaOvfBDyyfVMtfiDEUuQ==,type:comment]
#
#ENC[AES256_GCM,data:Fw/h6VjB/aTaXwnFLfu/Vgela5GDWyqtRWGH4G4kgTAHVzDOxlmGxyKNe+dyiLAILj0GyidHG7tlrcYxiRzuSkA+T45kEO+Q5JBPk5w=,iv:8XmwXPIwpcwcviT5IvOBfsHZsEgNDgKgjHzHbhT4Q9Q=,tag:cmyGEEePpBf/7TEZhYzG2g==,type:comment]
#ENC[AES256_GCM,data:c7D72OHZtWlYQ36REXKUawWy6OSvAs56sRhotmdk6yYvPUYCYKwFEHZ/ey9IyDxWO3LpItiSEwN4is+aQ16758XSzNUed51bt4M=,iv:xW4YUit2dmI1hMk0gwgsYF1r+Zkzs+aMvQbT7LWSp5E=,tag:vC8Z1XRNfbIXDqqUhfDusg==,type:comment]
#ENC[AES256_GCM,data:tdmiKw5WPSnYP8Lm+QUPOx4t4JMKjUabf3RndtAkG8UDKZTS/EYTzsdJOBT4CuDvxM/174OyeTB3SlnitXjy,iv:gSwxJ9cXUqZOkUUPAfVh/JqtXImQcUBeFAoXWuvavKM=,tag:GS6REjfkk3N1Zj8UfO3XPA==,type:comment]
#ENC[AES256_GCM,data:pPuvVCFu1oGPmsjtN+emye3i+gpOBGQ=,iv:XmuMcD9SyW7+7Z4Kn6KDN5nk35F0T5pW2b9xtGRn1PM=,tag:zkri1lPZnKhXL4A9uk8MpQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:dME=,iv:oiZWytEJqNhQO2t0QkHsoXEng7FXXhu+TyoCYwrExJE=,tag:HBrQRU11dn8COs04Ja9iVA==,type:str]
kind: ENC[AES256_GCM,data:cQZPsx6H,iv:91oSwWaUsLBF7ipkEo1CUqa32GXBSFufRzae4RWLrVY=,tag:jN6SWsR6p+md4au62aznvw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BG1+yCHvcQcBNpGK/zJR67ou,iv:P6jcIFS2/WThpaFEC/eEHxwidOys0B9gaGgVhB4vXHU=,tag:5zHgnxS+GDCtGdZvvnFV8A==,type:str]
    namespace: ENC[AES256_GCM,data:TAIY15GJ3GU1sw==,iv:HRszLcNzgCyx0IkaOPKfF/Nl8dcZZZ6Z/9zsuVfJOfI=,tag:zzGq7LgLiByGzGFhcqJPeQ==,type:str]
stringData:
    TOKEN: ENC[AES256_GCM,data:wEoSdGSgvSuo63oYhy4UpWKwFYY+cDFTaLhsznu2JGa1qG29qp+iI1YdXhINVdJ7XxnZZtQ676ZmOAQpb/Tm7g==,iv:47fXFSX3oTvpusd7lYJqnCMhZJWBrm6vmjLdaIFaOfg=,tag:mVsIpHEfMAEvxHfLHoSFnw==,type:str]
sops:
    age:
        - recipient: age19ucefxcdyvvyp373ghd4crdyudgw3l7adxneu3wmvus4vu3z5c5qqdm7cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTc1N6OHFra28rU1NmK3J3
            L3k3RVpMWC9Ea0xkYk5LN0dKV3A2aTZ5WkFrCjFiMTZsbHVCb0hML1N2cjFHdkJw
            TmM4WXErT1NIa1hIUk84ZEtUZ1NzY2cKLS0tIG05T2d3OXZURVhEczhaaU1pUkZt
            Ny8wbTRnMWdaY01jbDFLOGxsZE5pTU0KUgzKCWEZ7vbY2pXmdZnM+NZs4xVJPuMi
            3LfJ3hSDYYFqbYi1ai6jb9nnqKp6beS3QV4qVZu0f5ri0amy2fdAyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T14:25:03Z"
    mac: ENC[AES256_GCM,data:MvCK+pCCcdZOnBnapwjQyNTgZ8hc41o+5qsOQ50TthcMv7TusZ3XENZm8/hWUrkUUhvKFyEHEtD7qAExGohUpwfuIn+zhv1ZDSgqYxGKoPzZ1rEDdUgps6qtTvGk/g0xQEfatFlMw8FyIg4Rng42W3nf5eXlIj97pX60yCcdeiQ=,iv:F5ByPgvfRMCNEomQbnkXaPC+QCWi5aQ1aW2cQpyf6mU=,tag:b+YkuKOlfwWJ+snEZJ5Bcg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
