#ENC[AES256_GCM,data:WEKnj9FS7wD6RD78bym8lbO7/Gn6hi0YBq72UutaGPcfTiSCpo6dBf/2fV4ZzixL8eF30SKsw14x9/SxTgREQD8=,iv:4PeC1NTUYS2xa23ag1VYKwmLNXYQzGsDTGOU3TjVPBU=,tag:PyYgO9uh1VDnSuf+STXTaw==,type:comment]
#
#ENC[AES256_GCM,data:w30EDPSjO3U2AcOPXGWTGnwR5xDX9Y86zmbKDzvtuBajUv4Uiu9W/OkvwjQW5jH4YFfhoS+ZlLMjphl8gUKVIrq6LHG6NgXgZuTiIOw=,iv:XOFK0AnzgLsLEbyy1YwW1afaUYgL0cr8NsRsSCtkH6U=,tag:TQ9nrEg1Ueg/A6u7CFKA5w==,type:comment]
#ENC[AES256_GCM,data:Me3gy9WCJp/DjvnOmhJJoOMlARkOp7oOoNQ9YmGKxpwWJAuhA1lvLU+QilW5ve7jdU+VFUg3acnvcc7cGO5LGVoM2qfUw0a8OXo=,iv:3BxP/DSgUQnpdiOyv9Txa7DX8Ub2NcIAqQ4Q5v44pLQ=,tag:uUZwHq1HdMvAhQmlODzYJA==,type:comment]
#ENC[AES256_GCM,data:/5COc73+NDXPqtvk/5fe1yR3M8q5n7x3Le/FYL52hugsTCiirYC7/UCaaQiVvE7xaNxphE59r/0BvhFqzksz,iv:tMLPkJ98YoUE8bGiHu0PHVB/cS/SveBa+PQlaah3EwM=,tag:kGlqTlIV805zl6NNt4AQRA==,type:comment]
#ENC[AES256_GCM,data:f+PsrKX+55iFh+03jwSJEdLGRe/9J54=,iv:bzx8OydNmLN9qBveHN463x6JLDJrLaniQ2iS/2l/BDU=,tag:nGCvX0TQxGVL6yw+gXkcHQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:8oI=,iv:GSB7JY3BGDm9sS4si6BRDWoyNTp3q9PVm7y4aMOCups=,tag:nInECFqAwVdT0+YoZl1XUg==,type:str]
kind: ENC[AES256_GCM,data:lGpuTOhS,iv:2i7ZvbKppFzcEN5NeKjFUsVIkEYW+4JZRHGDTuSPkvQ=,tag:RhpxpoV+hPm4+UYIMN+a+Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:+Z7NVBb5/MtzvBXtvnHufmbG,iv:WIw+YSTYT8aYyZWOXZIFdZjZ/0CrQc1JzZENTTCt8AE=,tag:3mzw87ZkkojzhQMTZCplng==,type:str]
    namespace: ENC[AES256_GCM,data:+gEBub6mFEBLgA==,iv:Vx5SY1sIEs22Bp1+6Q73U5PBFTfEkF+OgBen81fIDA4=,tag:w4VqbSSlVE9gyyH6Jbm0Bg==,type:str]
stringData:
    TOKEN: ENC[AES256_GCM,data:0bIyrLdtC1hnhetamPssvRsrKTfrQzY1L11oLzRHgYJ4fbtdxztEUqJJGTsI1S8uO/SKe8hsk7/52jDRUrgGfA==,iv:HFlR9BTBRXKXbV8i3SpZDFSoWrjU9ycvNuTv6dLMI2s=,tag:pI/cGF9JIJxGWXwDtJxqlw==,type:str]
sops:
    age:
        - recipient: age19ucefxcdyvvyp373ghd4crdyudgw3l7adxneu3wmvus4vu3z5c5qqdm7cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBON3M4SHBjQ2MrRFk5VDJs
            RFc2R1FibnVPUEt3VEcyN0w2ekJBZmRha0JjCmwrcy9BUVpUYVk0ODM3SVVyd3BX
            S2t6VlU0czJ1NFYvbFFieHBvejEwZmMKLS0tIGNrdm4vSVhseDVoK2ZUNmt1SFNL
            N085dmhZQ2kwRjVPVUFmQTJlcjBuVlUKCbNUQeoz+m7oqAiEj8NsHXfpMnhN7ZWk
            YUASpHNcP815yuBnBC8JtAwJNLtZU83oFRl4oSXLIL+pu6IcqnqgPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T14:44:23Z"
    mac: ENC[AES256_GCM,data:yc1pp5P90PMNhtGTTeLYAxmcgBCwj4DgZs3SPVHVwK1yD4+aUq15/dDbwCYUGp9eXM0gYUnkIGAMLba9df1v7ok9Ol79L1DoG4a4+MmldHhR0PeihoU4AYHa/zrpVk3Ic/mpNNwc6aNQt2nWw1cfcytEUkv0l6iyYYfBLn054yI=,iv:Xcz9vVmUDC2Vo7FQcmK6auFf1O87LKJjHRdTCOSLeL0=,tag:iAQuGLXBAKDoTkZrEU2wiw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
