#ENC[AES256_GCM,data:mIGRuEukIwic5iIDjnks3vD8UGKmCs5wdFWHXqAXZ4ybkPgrtV2TA9nRAItpXQaplKKwnlNamdbRYaPGRTgSS5M=,iv:3WCgConTIAj9cMjNEjFB8MwSkW9ldazHPPe+G+oscmI=,tag:w0BxCRKTxUPZ2vHZ5wbaZQ==,type:comment]
#
#ENC[AES256_GCM,data:gzYMfaBk8MIfU2BXtbbKLJLAOjF06IK4qdU7WkDJIMmAnUHuYqhpTFM/HsYAg9DLjfkwn2K8CuJTM6mX9WYZY7ySSZiwNG3N0DKCgfo=,iv:szsMKAhzNPg2WnJdt08i39Jz0HGgW5EQLb3gkcdW2IU=,tag:FvPLB4ruW3q+8Vg5epOSbg==,type:comment]
#ENC[AES256_GCM,data:LpiT25bqUJtqbOvoB2DooDYTML7yiDl5oFoggjzNIA7nNZKFdXz1Hoj6Hcz90J2B7fAicnyWyYFqsvTx9AyfSHxzZ5+ltIUDS0Q=,iv:xNYLLPwdJgDRJ0eXfzRZLUc78W0CzkBDur463x6dG+A=,tag:EAZOXOl7v0b+rI1Sx7hgsw==,type:comment]
#ENC[AES256_GCM,data:yoalk6gGqncLghsPaaKogLT8NTGIYZGRJpxXMjQqAL+yt5rnDvLX4OUZdyTLPaamR+LlHBSTlF6PzN7DKG73,iv:m6HT4RUsMXMR3UEhlzwP7SRe4DACHuvKRv/mh+xvDww=,tag:0wGK0deJdGoBY1L2h99WhQ==,type:comment]
#ENC[AES256_GCM,data:1eu9b5Wl/swaAljcfGBbatHa53jCi1Q=,iv:2E/QFvuOzndfLCelWx0NL/KCYZRBvGVyHVlB7fbhS+g=,tag:KYXxJHw6LeHNtrePDXJvNA==,type:comment]
apiVersion: ENC[AES256_GCM,data:oCA=,iv:bDhFU79KiA8bUAoXN/FIwytWNfLOMrk+z3d2fLDrNik=,tag:ZyxnWtUHaX7q21ZgO/7r1Q==,type:str]
kind: ENC[AES256_GCM,data:AzVEyvT8,iv:1S2tEWOPBFpE2/BL+kPICTOnQSeyW9FnwdALgb/2R8s=,tag:1sQS+1/tsZ7lYOyksetEew==,type:str]
metadata:
    name: ENC[AES256_GCM,data:bjnf+63DwAx3eE5HznQu+OIN,iv:Y+6xSBi7fW9srJ2L0f2AZ8vgPhHHriiiAcyLM9dIqQs=,tag:MoSX956CnohQefCpdyrKUA==,type:str]
    namespace: ENC[AES256_GCM,data:nu1fFhJPhZc0vQ==,iv:VbXZozmhx+nmryxL4M8l4J7w+E6hHaqqC782n+Jrn5c=,tag:176Z5PKhK0LAJ7Dsd7/vgA==,type:str]
stringData:
    TOKEN: ENC[AES256_GCM,data:lGoAYcIERoVcBi5v3vjSwSvxe6fkbyBd3kTLYozV39qbk3VxLMjN75qe646HegNGggUiS/AhkW/JFxx+lTQMnQ==,iv:IByOcMhKgKEvz9ZQ5S//QuLYBWWnwDmKYSamtj6Rd+c=,tag:1BSsVMAhIwL/pwx3XxolQQ==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:YRof6w+h8GYp27AB5gwX/J+vxw8lr143GRA3j+pWcQTKcaQzBa475PiPnpOpRX/4Z4GII+3awiA0nktZ3c3n8Q==,iv:X8KqoI78llGKHlK2SuXnzH8Y2xvxZQzZGKla99+/Evw=,tag:frRCmKWcvfpsPOrnfxBT8A==,type:str]
sops:
    age:
        - recipient: age19ucefxcdyvvyp373ghd4crdyudgw3l7adxneu3wmvus4vu3z5c5qqdm7cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Y0tSczBwTGJma3M3NmFo
            VEJJUTltMU9vbGVLckhkUFdhcXdNdUhEMXk0ClFBTzdaMTlaSVF0UzVJUG5sb00z
            aHg2Z3M5clRQUTg1WmxseUVSVjFraGMKLS0tIGFLU2p5WmhleGdZMkFXcXpKMU9y
            OExYTEdhUGlaeDVTWXRZZXd6WWpMSFEKgwgwJAGyynSCF0YKWyXk2m/FqshmL5z0
            dr+SU/xXXwAkgr4yjAFM7BYhe1sjtymjFralv/YBDYvqZa1Imp3SVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-25T13:44:55Z"
    mac: ENC[AES256_GCM,data:OliogMdTyVcYoAmI+zH2scdG85FwjuMgIFKWvSecIEg9J2sOg65GUisFs+n6gzTscqwls1Wpp09OzM+oxpS9C2f5f+qwcl9DnGmgzTveltx/MWm1cCsQ28NAcZ+uM3gVyIHg9P7Sn6nyVC30yJdvySOJ4Afm+En7ER9Um1qH2lM=,iv:HLxpUzXb9hFqLv3gK1zqYhya/Al012TTAQQo1rUTUcs=,tag:p0PoeHafAlYo8hrl3wbzTQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
