#ENC[AES256_GCM,data:SSVd18mvY7ybzTgTCRfMb3ggcaUzTD1QZUEzz7BkM03PKtJPJca8Kz6r5sK2t7yS5TZdaRGo3dsb81i6DIp+13+G7fY=,iv:iqvLZl9wl1WhUToCdZYnboJiN3vj2NjEtxQJxBumoxs=,tag:gqE5eAjfIc1EN2jWhpnLOg==,type:comment]
#
#ENC[AES256_GCM,data:PTQbWMMK5I/G7OEvSvXYWZMBsanZyhydmNrUXT+68SmU7eNgj6QI280v3p3dYdPu7xKCWxjDa1eVn+jGQDvXR4AIvr3X0HxT9KM=,iv:XZlkfwXXLW3gMkZEV7gqff8B0PMbNTTSKVEjpqE+O+8=,tag:N/HMBfkSu214hfXhclahjA==,type:comment]
#ENC[AES256_GCM,data:Fk8zWfoR1+VYEpoFThn9ScekJTRHZxMbChphBa+HiZXq+JrBpc5Yupe7cVqpaH5yZ5yHhiv/VfPiQepWxTilccAdyi0=,iv:4L51IzxSw2V3Oec6/5rgDtwfUj3ZtUd92TRPtDblC/I=,tag:gqoc+LsRYlwefENzOuxDHg==,type:comment]
#ENC[AES256_GCM,data:SEodHBnoRzCtCx8BA5RS3Vd7j3/W0kZp8zh5e+8/50oL,iv:FfOlLHeIIbnHk4FUy2GudeLgsgPgUrOlecwwMH1903w=,tag:movKc6gRuLB/DQ83lsBtXw==,type:comment]
apiVersion: ENC[AES256_GCM,data:Gdo=,iv:7E4DjdNmbbvgdCaxj2VVrhBXw9EbIFH+awmiYIA4oIM=,tag:4nMq27FZqBoIIn4G7zUuKw==,type:str]
kind: ENC[AES256_GCM,data:DbQtUzGk,iv:wRHC+pL58KFv+lTBHqyxhFzrE4SEfGMM956YektlTTE=,tag:9NB7+ofOAXAFYS9uvpCTkg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1FZY4y06GGqtD2lhisp/1GrM,iv:HqQZoQZCvWPPhzpIc6HCd+B9r46hkejzK7JkV0PQdTc=,tag:rLlsdE2fggPXzadisBWqgw==,type:str]
    namespace: ENC[AES256_GCM,data:Oz6XDKCDfoWBrg==,iv:90LouLSR3B2lK7WddGZk3gizthwTNbPTH475zWx1+dQ=,tag:mUiuGRVHrcS2WALKuz3TiA==,type:str]
stringData:
    PGDATABASE: ENC[AES256_GCM,data:1lGkb6Aa5+Twzg==,iv:X4mJfyL/6nhxh+gxrY8Vab1n+sv1waItJYMv5P6RaMM=,tag:rf15wywWLsc4vkGH5m2I5A==,type:str]
    PGUSER: ENC[AES256_GCM,data:S5GjWPospjb73A==,iv:b4miGHObnz/w0t08ji0iV/pqJ3e5VuTdFN4mdm1MqWM=,tag:oFlpPC0EsSf9MyX/2zbCPQ==,type:str]
    PGPASSWORD: ENC[AES256_GCM,data:y7mTS+pChLQO0TdQ8Tl1BA==,iv:+gAvQSRklptDMp/wH40KXzHXdJyB+uJy0iCjFmI+faM=,tag:wQJiiraCJaIaMQ+ePzwMOw==,type:str]
sops:
    age:
        - recipient: age19ucefxcdyvvyp373ghd4crdyudgw3l7adxneu3wmvus4vu3z5c5qqdm7cj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbzFxTEZDR0lWSWJPQkxL
            TlRPNi9kSVk1a2FuL080ZVF2RGdZZys1NldnCk5BbXlpRXpXOUpJenRFWEdxeTVy
            WUpWemhBd2pTdHJJb09CTWdidlA1T0EKLS0tIGEwNjlXUktlTDdvbng1YWRBZmw5
            WEdFbXBrM1dRYy9xS3JaekliUm8xRGMKVh2XRe4pLnP4V45mfsZ/Cg/2hPn/s4+r
            PDkf9prSZUlh3gX+RbZ1vVCoqH92lNX/iK9/3yiRa6vSUsVFhKnPnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T14:44:23Z"
    mac: ENC[AES256_GCM,data:EE6KSBXc8whkqupzc2li7smpPNncRQ5j76K7LNgqP+ra3DsluD5h3FEAIbcsdxcjzkGDi/XIGD1GNhJmzstK2S6ml4InwSfGtuogxJZohKOjuZml7lA+8bJPxDFnrnKvfHNceXNS0mW/3DYbenDPJIvDivI85q5LkObmBsmMUCo=,iv:j7NtdQEgntx9QuZmPjCIUoMciMb2SF4pGDK5hxfG12U=,tag:+j3vW0Bs3CbXXboe7BSLVw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
